---
- hosts: webservers
  tasks:
    - name: install nginx
      apt: name=nginx state=latest
    - name: start nginx
      service:
        name: nginx
        state: started
    - name: configure nginx
      copy:
        src: etc/nginx/sites-available/static_site.conf
        dest: /etc/nginx/sites-available/default.cfg
    - name: put in index.html
      copy:
        src: var/www/html/index.html
        dest: /var/www/html/index.html
    - name: reload nginx
      service:
        name: nginx
        state: reloaded

